---
- name: Create iredmail directory
  file:
    path: "{{ IREDMAIL_DATA_DIR }}"
    state: directory
- name: Untemplatet iredmail-docker.conf
  template:
    src: iredmail-docker.conf.j2
    dest: "{{ IREDMAIL_DATA_DIR }}/iredmail-docker.conf"
- name: Stop container if exists
  docker_container:
    name: iredmail
    state: absent
    force_kill: true
- name: Remove image
  docker_image:
    state: absent
    name: iredmail/mariadb
    tag: nightly
    force_absent: true
- name: Run iredmail
  docker_container:
    name: iredmail
    image: iredmail/mariadb:nightly
    restart_policy: always
    env_file: "{{ IREDMAIL_DATA_DIR }}/iredmail-docker.conf"
    hostname: "{{ HOSTNAME }}"
    ports:
      - 880:80
      - 8443:443
      - 110:110
      - 995:995
      - 143:143
      - 993:993
      - "25:25"
      - 465:465
      - 587:587
    volumes:
      - "{{ IREDMAIL_DATA_DIR }}/backup:/var/vmail/backup"
      - "{{ IREDMAIL_DATA_DIR }}/mailboxes:/var/vmail/vmail1"
      - "{{ IREDMAIL_DATA_DIR }}/mlmmj:/var/vmail/mlmmj"
      - "{{ IREDMAIL_DATA_DIR }}/mlmmj-archive:/var/vmail/mlmmj-archive"
      - "{{ IREDMAIL_DATA_DIR }}/imapsieve_copy:/var/vmail/imapsieve_copy"
      - "{{ IREDMAIL_DATA_DIR }}/custom:/opt/iredmail/custom"
      - "{{ IREDMAIL_DATA_DIR }}/ssl:/opt/iredmail/ssl"
      - "{{ IREDMAIL_DATA_DIR }}/mysql:/var/lib/mysql"
      - "{{ IREDMAIL_DATA_DIR }}/clamav:/var/lib/clamav"
      - "{{ IREDMAIL_DATA_DIR }}/sa_rules:/var/lib/spamassassin"
      - "{{ IREDMAIL_DATA_DIR }}/postfix_queue:/var/spool/postfix"
